{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-openalexr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/openalexR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/openalexR/openalexR_{{ version }}.tar.gz
  sha256: 1369e5c4954ab7434298454729bfac96bd9efdfd33ec9152651d81a3bb1f2306

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
    - r-tibble
  run:
    - r-base
    - r-httr
    - r-jsonlite
    - r-progress
    - r-tibble

test:
  commands:
    - $R -e "library('openalexR')"           # [not win]
    - "\"%R%\" -e \"library('openalexR')\""  # [win]

about:
  home: https://github.com/ropensci/openalexR
  doc_url: https://docs.ropensci.org/openalexR/
  license: MIT
  summary: A set of tools to extract bibliographic content from 'OpenAlex' database using API
    <https://docs.openalex.org>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: openalexR
# Title: Getting Bibliographic Records from 'OpenAlex' Database Using 'DSL' API
# Version: 1.2.0
# Authors@R: c( person(given = "Massimo", family = "Aria", role = c("aut", "cre", "cph"), email = "aria@unina.it", comment = c(ORCID = "0000-0002-8517-9411")), person(given = "Corrado", family = "Cuccurullo", role = c("ctb"), email = "cuccurullocorrado@gmail.com", comment = c(ORCID = "0000-0002-7401-8575")), person(given = "Trang", family = "Le", role = "aut", email = "grixor@gmail.com", comment = c(ORCID = "0000-0003-3737-6565")), person(given = "June", family = "Choe", role = c("ctb"), email = "jchoe001@gmail.com", comment = c(ORCID = "0000-0002-0701-921X")) )
# Description: A set of tools to extract bibliographic content from 'OpenAlex' database using API <https://docs.openalex.org>.
# License: MIT + file LICENSE
# URL: https://github.com/ropensci/openalexR, https://docs.ropensci.org/openalexR/
# BugReports: https://github.com/ropensci/openalexR/issues
# Imports: httr, jsonlite, progress, tibble
# Suggests: testthat (>= 3.0.0), dplyr, knitr, rmarkdown, tidyr, purrr, ggplot2, covr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# Config/testthat/edition: 3
# Depends: R (>= 2.10)
# NeedsCompilation: no
# Packaged: 2023-08-08 09:45:17 UTC; massimoaria
# Author: Massimo Aria [aut, cre, cph] (<https://orcid.org/0000-0002-8517-9411>), Corrado Cuccurullo [ctb] (<https://orcid.org/0000-0002-7401-8575>), Trang Le [aut] (<https://orcid.org/0000-0003-3737-6565>), June Choe [ctb] (<https://orcid.org/0000-0002-0701-921X>)
# Maintainer: Massimo Aria <aria@unina.it>
# Repository: CRAN
# Date/Publication: 2023-08-08 12:50:02 UTC
